# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Build and test pyqtkeybind

on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    env:
      DISPLAY: ':99.0'
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r development.txt; fi
        # See https://pytest-qt.readthedocs.io/en/latest/troubleshooting.html#github-actions
        sudo apt-get update -y
        sudo apt-get install -y --no-install-recommends \
          '^libxcb.*-dev' \
          libx11-xcb-dev \
          libglu1-mesa-dev \
          libxrender-dev \
          libxi-dev \
          libxkbcommon-dev \
          libxkbcommon-x11-dev \
          xvfb
    - name: Test with pytest
      run: |
        xvfb-run --auto-servernum pytest
    - name: Upload coverage results
      uses: codecov/codecov-action@v2.1.0
